name: "Test devenv"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: nix develop --no-pure-eval --command devenv "test"
