name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
          matrix:
            toolchain:
              - stable
              - beta
              - nightly
    steps:
    - uses: actions/checkout@v4
    - name: Init
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    strategy:
          matrix:
            toolchain:
              - stable
              - beta
              - nightly
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Init
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Update
        run: cargo update --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

